version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - "TZ=Europe/Amsterdan"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"