version: '3.8'

services:
  postgres: 
    image: postgres
    container_name: ldigital
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=ldigital
      - POSTGRES_PASSWORD=ldigital
      - POSTGRES_DB=ldigital
  
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ldigital@ldigital.com"
      PGADMIN_DEFAULT_PASSWORD: "ldigital"
    ports:
      - "80:80"
    depends_on: 
      - postgres